/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as CognitiveMapsRouteImport } from './routes/cognitive-maps'
import { Route as HistoricalContextRouteImport } from './routes/historical-context'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResearchVaultRouteImport } from './routes/research-vault'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SynthesisRouteImport } from './routes/synthesis'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveMapsRoute = CognitiveMapsRouteImport.update({
  id: '/cognitive-maps',
  path: '/cognitive-maps',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalContextRoute = HistoricalContextRouteImport.update({
  id: '/historical-context',
  path: '/historical-context',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchVaultRoute = ResearchVaultRouteImport.update({
  id: '/research-vault',
  path: '/research-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SynthesisRoute = SynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/cognitive-maps': typeof CognitiveMapsRoute
  '/historical-context': typeof HistoricalContextRoute
  '/login': typeof LoginRoute
  '/research-vault': typeof ResearchVaultRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/synthesis': typeof SynthesisRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/cognitive-maps': typeof CognitiveMapsRoute
  '/historical-context': typeof HistoricalContextRoute
  '/login': typeof LoginRoute
  '/research-vault': typeof ResearchVaultRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/synthesis': typeof SynthesisRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/cognitive-maps': typeof CognitiveMapsRoute
  '/historical-context': typeof HistoricalContextRoute
  '/login': typeof LoginRoute
  '/research-vault': typeof ResearchVaultRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/synthesis': typeof SynthesisRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archives'
    | '/cognitive-maps'
    | '/historical-context'
    | '/login'
    | '/research-vault'
    | '/security'
    | '/settings'
    | '/synthesis'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archives'
    | '/cognitive-maps'
    | '/historical-context'
    | '/login'
    | '/research-vault'
    | '/security'
    | '/settings'
    | '/synthesis'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/archives'
    | '/cognitive-maps'
    | '/historical-context'
    | '/login'
    | '/research-vault'
    | '/security'
    | '/settings'
    | '/synthesis'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivesRoute: typeof ArchivesRoute
  CognitiveMapsRoute: typeof CognitiveMapsRoute
  HistoricalContextRoute: typeof HistoricalContextRoute
  LoginRoute: typeof LoginRoute
  ResearchVaultRoute: typeof ResearchVaultRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SynthesisRoute: typeof SynthesisRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-maps': {
      id: '/cognitive-maps'
      path: '/cognitive-maps'
      fullPath: '/cognitive-maps'
      preLoaderRoute: typeof CognitiveMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical-context': {
      id: '/historical-context'
      path: '/historical-context'
      fullPath: '/historical-context'
      preLoaderRoute: typeof HistoricalContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-vault': {
      id: '/research-vault'
      path: '/research-vault'
      fullPath: '/research-vault'
      preLoaderRoute: typeof ResearchVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthesis': {
      id: '/synthesis'
      path: '/synthesis'
      fullPath: '/synthesis'
      preLoaderRoute: typeof SynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivesRoute: ArchivesRoute,
  CognitiveMapsRoute: CognitiveMapsRoute,
  HistoricalContextRoute: HistoricalContextRoute,
  LoginRoute: LoginRoute,
  ResearchVaultRoute: ResearchVaultRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SynthesisRoute: SynthesisRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
